#!/usr/bin/env bash

SCRIPTPATH="$(
  cd "$(dirname "$0")" || exit 1
  pwd -P
)"
export SCRIPTPATH

#if path to liblinkt is not not exported do so:
if [ -z "$LD_LIBRARY_PATH" ]; then
  export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/lib"
fi

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
  /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH/down" /tmp/leftwm-theme-down

# start eww daemon
eww daemon &

# Boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom --experimental-backends &>/dev/null &
  # picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &>/dev/null &
fi

# Set the theme.ron config
leftwm-command "LoadTheme $SCRIPTPATH/theme.ron"

# Set background
if [ -x "$(command -v nitrogen)" ]; then
  nitrogen --restore
fi
sleep 1
eww open bar
