#!/usr/bin/env bash

window=$(cat /proc/$(xdotool getwindowpid $(xdotool getwindowfocus))/comm)
title=$(xdotool getactivewindow getwindowname)

if [[ $window == "" || $title == "" ]]; then
  echo "Desktop"
  exit 0
fi

# fix .<program>-wrappe name
if [[ $window == .*-w* ]]; then
  window=$(cut -f2 -d. <<<"$window" | cut -f1 -d-)
fi

# uppercase first char
window=${window^}

# fix long string with window name in end of tiitle
if [[ $title == *$window ]]; then
  if [[ $title == *—* ]]; then
    title=${title%—*}
  elif [[ $title == *–* ]]; then
    title=${title%–*}
  fi
fi

if [[ $window == $title ]]; then
  toshow="$window"
else
  toshow="$window - $title"
fi
maxlen=70
sufix=""

if test $(wc -c <<<$toshow) -ge $maxlen; then
  sufix=" ..."
fi

echo "${toshow:0:$maxlen}$sufix"
